---
- name: setup vagrant-anaconda
  hosts: vagrant
  user: vagrant
  sudo: true
  gather_facts: False

  pre_tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

  tasks:
    - name: test connection
      ping:

    - name: add my machine's ssh key to vagrant authorized_keys
      authorized_key: user=vagrant key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    - name: download anaconda installer
      get_url: url=https://repo.anaconda.com/archive/Anaconda3-5.3.0-Linux-x86_64.sh dest=/etc/Anaconda3-5.3.0-Linux-x86_64.sh

    - name: install anaconda
      shell: /bin/bash /etc/Anaconda3-5.3.0-Linux-x86_64.sh -u -b -p /opt/conda

    - name: add anaconda to bashrc
      shell: echo ". /opt/conda/etc/profile.d/conda.sh" >> /home/vagrant/.bashrc

    - name: add conda to bashrc
      lineinfile: 
        dest: /home/vagrant/.bashrc 
        line: export "PATH=/opt/conda/bin:$PATH"
        insertafter: 'EOF'
        state: present

    - name: install required packages
      shell: /bin/bash -c "/opt/conda/bin/conda install {{item}} -y --quiet"
      with_items:
        - jupyter
        - sqlalchemy
        - pymysql
        - sqlite
        
    - include: mysql_install.yml

    - name: copy upstart file
      template: src=notebook.service dest=/etc/systemd/system/notebook.service
    
    - name: fix permission
      file: path=/etc/systemd/system/notebook.service owner=root group=root mode=0644
    
    - name: enable notebook on boot
      systemd:
        name: notebook
        enabled: yes
        daemon_reload: yes